### PR TITLE
Rename test files to work for Windows builds

### PR DESCRIPTION
**Pull request by earlephilhower**
Windows doesn't like :s in its filenames, so replace them with
underscores and update the expected test outputs accordingly.

### CODE REVIEW

**Comment by pfalcon** [comment]
Thanks for the patch, but: 233 changed files O_o. I'm not sure I love Windows that much ;-).

**Comment by earlephilhower** [comment]
True, but it's nothing more than a scripted `git mv` to rename them from : to `_`s.

Don't get me wrong, it's not like I love Windows that much, either  On the ESP8266 code we do builds for Linux X64, OSX, LinuxARM, and Windows as part of CI and git just completely barfs on Win32 when it gets a file with a : in it.

**Comment by pfalcon** [comment]
Yeah, I understand, it's just I do my homework to maintain clean project history and avoid sweeping changes, so it's a bit hard to swallow contributions like this ;-). Again, let me take some time to come to peace with it ;-). Perhaps, make a repo rebase? :-D (These files were contributed either, and I took them as is.)

**Comment by d-a-v** [comment]
I'd suggest to just tar-gzip9-all-of-them into a single one file for everyone's peace ;)

**Comment by earlephilhower** [comment]
For this one, I'm fine dropping it.  If #27 merges here, it may be worth patching the ESP8266 CI to just not pull the uzlib submodule or something, but for now we can continue with the forked version.

Thanks again!

**Comment by pfalcon** [comment]
I actually was looking for a feedback regarding squash-rebase proposal (I myself fully ok with it, but would like to hear what downstream users might say...). Well, I assume it's easier to leave it as is for now...

**Pull request closed without merging**
